---
- name: install remi repository
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: install php
  yum: name={{ item }} enablerepo=remi,remi-php56 state=present
  with_items:
    - php
    - php-cli
    - php-gd
    - php-mbstring
    - php-mysqlnd
    - php-opcache
    - php-pdo
    - php-pecl-memcache
    - php-xml

- name: create php config
  copy: src=99-my.ini dest=/etc/php.d/99-my.ini owner=root group=root mode=0644
